#:schema node_modules/wrangler/config-schema.json
name = "leetcode-bot"
main = "./src/server.js"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat"]
[observability]
enabled = true

